kata_pendu/kata_pendu/Models/Dictionnary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace kata_pendu.Models
{
    public class Dictionnary
    {
        public int Id { get; set;}
        public string Word { get; set; }
    }
}

kata_pendu/kata_pendu/Models/ErrorViewModel.cs
using System;

namespace kata_pendu.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

kata_pendu/kata_pendu/Controllers/DictionnariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kata_pendu.Models;
using System.Text;
using System.Globalization;

namespace kata_pendu.Controllers
{
    public class DictionnariesController : Controller
    {
        private readonly kata_penduContext _context;

        public DictionnariesController(kata_penduContext context)
        {
            _context = context;
        }

        // GET: Dictionnaries
        public async Task<IActionResult> Index()
        {
            return View(await _context.Dictionnary.ToListAsync());
        }

        // GET: Dictionnaries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dictionnary = await _context.Dictionnary
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dictionnary == null)
            {
                return NotFound();
            }

            return View(dictionnary);
        }

        // GET: Dictionnaries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dictionnaries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Word")] Dictionnary dictionnary)
        {
            if (ModelState.IsValid)
            {
                dictionnary.Word = RemoveDiacritics(dictionnary.Word);
                _context.Add(dictionnary);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dictionnary);
        }

        // GET: Dictionnaries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dictionnary = await _context.Dictionnary.FindAsync(id);
            if (dictionnary == null)
            {
                return NotFound();
            }
            return View(dictionnary);
        }

        // POST: Dictionnaries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Word")] Dictionnary dictionnary)
        {
            if (id != dictionnary.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dictionnary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DictionnaryExists(dictionnary.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dictionnary);
        }

        // GET: Dictionnaries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dictionnary = await _context.Dictionnary
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dictionnary == null)
            {
                return NotFound();
            }

            return View(dictionnary);
        }

        // POST: Dictionnaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dictionnary = await _context.Dictionnary.FindAsync(id);
            _context.Dictionnary.Remove(dictionnary);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<JsonResult> GetRandomWord()
        {
            Random random = new Random();
            var dictionnary = await _context.Dictionnary.ToListAsync();
            int rand = random.Next(dictionnary.Count());
            var word = dictionnary[rand];
            return Json(word);
        }

        public string RemoveDiacritics(string str)
        {
            if (null == str) return null;
            var chars =
                from c in str.Normalize(NormalizationForm.FormD).ToCharArray()
                let uc = CharUnicodeInfo.GetUnicodeCategory(c)
                where uc != UnicodeCategory.NonSpacingMark
                select c;

            var cleanStr = new string(chars.ToArray()).Normalize(NormalizationForm.FormC);

            return cleanStr;
        }

        private bool DictionnaryExists(int id)
        {
            return _context.Dictionnary.Any(e => e.Id == id);
        }
    }
}

kata_pendu/kata_pendu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using kata_pendu.Models;

namespace kata_pendu.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

kata_pendu/kata_pendu/Views/Dictionnaries/Create.cshtml
@model kata_pendu.Models.Dictionnary

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Dictionnary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Word" class="control-label"></label>
                <input asp-for="Word" class="form-control" />
                <span asp-validation-for="Word" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

kata_pendu/kata_pendu/Views/Dictionnaries/Delete.cshtml
@model kata_pendu.Models.Dictionnary

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dictionnary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Word)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Word)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

kata_pendu/kata_pendu/Views/Dictionnaries/Details.cshtml
@model kata_pendu.Models.Dictionnary

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Dictionnary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Word)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Word)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

kata_pendu/kata_pendu/Views/Dictionnaries/Edit.cshtml
@model kata_pendu.Models.Dictionnary

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Dictionnary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Word" class="control-label"></label>
                <input asp-for="Word" class="form-control" />
                <span asp-validation-for="Word" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

kata_pendu/kata_pendu/Views/Dictionnaries/Index.cshtml
@model IEnumerable<kata_pendu.Models.Dictionnary>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Word)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Word)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

kata_pendu/kata_pendu/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<script src="/lib/jquery/dist/jquery.js"></script>
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>


<a id="Proposition" style="margin-bottom:10px"></a>


<br />

Lives left : <a id="Life"></a>

<br />
<button id="A" class="letter" onclick="Propose('A')">A</button>
<button id="B" class="letter" onclick="Propose('B')">B</button>
<button id="C" class="letter" onclick="Propose('C')">C</button>
<button id="D" class="letter" onclick="Propose('D')">D</button>
<button id="E" class="letter" onclick="Propose('E')">E</button>
<button id="F" class="letter" onclick="Propose('F')">F</button>
<button id="G" class="letter" onclick="Propose('G')">G</button>
<button id="H" class="letter" onclick="Propose('H')">H</button>
<button id="I" class="letter" onclick="Propose('I')">I</button>
<button id="J" class="letter" onclick="Propose('J')">J</button>

<button id="K" class="letter" onclick="Propose('K')">K</button>
<button id="L" class="letter" onclick="Propose('L')">L</button>
<button id="M" class="letter" onclick="Propose('M')">M</button>
<button id="N" class="letter" onclick="Propose('N')">N</button>
<button id="O" class="letter" onclick="Propose('O')">O</button>
<button id="P" class="letter" onclick="Propose('P')">P</button>
<button id="Q" class="letter" onclick="Propose('Q')">Q</button>
<button id="R" class="letter" onclick="Propose('R')">R</button>
<button id="S" class="letter" onclick="Propose('S')">S</button>
<button id="T" class="letter" onclick="Propose('T')">T</button>

<button id="U" class="letter" onclick="Propose('U')">U</button>
<button id="V" class="letter" onclick="Propose('V')">V</button>
<button id="W" class="letter" onclick="Propose('W')">W</button>
<button id="X" class="letter" onclick="Propose('X')">X</button>
<button id="Y" class="letter" onclick="Propose('Y')">Y</button>
<button id="Z" class="letter" onclick="Propose('Z')">Z</button>

<br />
<button onclick="document.location.reload()" style="margin-top:50px" > New game</button>

<script>
    var solution = "";
    var life = 10;
    var table = [solution.length];
    var trouve = false;

    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            url: '/dictionnaries/GetRandomWord',
            success: function (result) {
                solution = result.word.toUpperCase();
                for (var i = 0; i < solution.length; i++) {
                    if (solution[i] >= 'A' && solution[i] <= 'Z') {
                        table[i] = '_';
                    }
                    else {
                        table[i] = solution[i];
                    }
                }
                game();
            }
        })



    })

    function Propose(letter) {
        var old = table.slice(0, table.length);
        for (var i = 0; i < solution.length; i++) {
            if (letter == solution[i]) {
                table[i] = letter;
            }
        }
        if (old.toString() == table.toString()) {
            life -= 1;
        }
        var button = document.getElementById(letter);
        button.disabled = true;

        game();
    }

    function game() {



        var word = table.toString().replace(/,/g, '');
        var proposition = document.getElementById('Proposition');
        proposition.innerText = word;

        var lives = document.getElementById('Life');
        lives.innerText = life;

        if (word == solution) {
            trouve = true;
        }

        if (trouve) {
            var buttons = document.getElementsByClassName("letter");
            for (var i = 0; i < buttons.length; i++) {
                buttons[i].disabled = true;
            }
            alert("You win!");
        }
        if (life == 0) {
            var buttons = document.getElementsByClassName("letter");
            for (var i = 0; i < buttons.length; i++) {
                buttons[i].disabled = true;
            }
            alert("You loose: The word was: " + solution);
        }


    }
</script>

kata_pendu/kata_pendu/Views/Home/Test.cshtml
@{
    ViewData["Title"] = "Test";
}

<h1>Test</h1>

<script src="/lib/jquery/dist/jquery.js"></script>
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>


<div>
    Remplacement des bonnes lettres:
    <a id="Test_remplacement1"></a>
    <a id="Test_remplacement2"></a>
    <a id="Test_remplacement3"></a>
</div>

<div>
    Victoire: 
    <a id="Test_victoire"></a>
</div>

<div>
    Perte de chance:
    <a id="Test_pertevie"></a>
    <a id="Test_nonpertevie"></a>
</div>

<div>
    Défaite:
    <a id="Test_defaite"></a>
</div>

<script>
    var solution = "TEST";
    var life = 10;
    var table = ['_','_','_','_'];
    var word = "";
    var trouve = false;

    $(document).ready(function () {
        game()
        Propose('T');
        if (word == "T__T") {
            var proposition = document.getElementById('Test_remplacement1');
            proposition.innerText = "OK";
            proposition.style.color = "green";
        }
        else {
            var proposition = document.getElementById('Test_remplacement1');
            proposition.innerText = "KO";
            proposition.style.color = "red";
        }
        Propose('E');
        if (word == "TE_T") {
            var proposition = document.getElementById('Test_remplacement2');
            proposition.innerText = "OK";
            proposition.style.color = "green";
        }
        else {
            var proposition = document.getElementById('Test_remplacement2');
            proposition.innerText = "KO";
            proposition.style.color = "red";
        }
        Propose('R')
        if (word == "TE_T") {
            var proposition = document.getElementById('Test_remplacement3');
            proposition.innerText = "OK";
            proposition.style.color = "green";
        }
        else {
            var proposition = document.getElementById('Test_remplacement3');
            proposition.innerText = "KO";
            proposition.style.color = "red";
        }
        Propose('S')
        if (word == "TEST" && trouve == true) {
            var proposition = document.getElementById('Test_victoire');
            proposition.innerText = "OK";
            proposition.style.color = "green";
        }
        else {
            var proposition = document.getElementById('Test_victoire');
            proposition.innerText = "KO";
            proposition.style.color = "red";
        }


        solution = "TEST";
        life = 3;
        table = ['_', '_', '_', '_'];
        word = "";
        trouve = false;
        Propose('R');
        if (life == 2) {
            var proposition = document.getElementById('Test_pertevie');
            proposition.innerText = "OK";
            proposition.style.color = "green";
        }
        else {
            var proposition = document.getElementById('Test_pertevie');
            proposition.innerText = "KO";
            proposition.style.color = "red";
        }
        Propose('S');
        if (life == 2) {
            var proposition = document.getElementById('Test_nonpertevie');
            proposition.innerText = "OK";
            proposition.style.color = "green";
        }
        else {
            var proposition = document.getElementById('Test_nonpertevie');
            proposition.innerText = "KO";
            proposition.style.color = "red";
        }
        Propose('F');
        Propose('Y');
        if (life == 0) {
            var proposition = document.getElementById('Test_defaite');
            proposition.innerText = "OK";
            proposition.style.color = "green";
        }
        else {
            var proposition = document.getElementById('Test_defaite');
            proposition.innerText = "KO";
            proposition.style.color = "red";
        }
    })

    function Propose(letter) {
        var old = table.slice(0, table.length);
        for (var i = 0; i < solution.length; i++) {
            if (letter == solution[i]) {
                table[i] = letter;
            }
        }
        if (old.toString() == table.toString()) {
            life -= 1;
        }

        game();
    }

    function game() {



        word = table.toString().replace(/,/g, '');


        if (word == solution) {
            trouve = true;
        }

        if (trouve) {
            
            alert("You win!");
        }
        if (life == 0) {
            
            alert("You loose: The word was: " + solution);
        }


    }
</script>

kata_pendu/kata_pendu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - kata_pendu</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">kata_pendu</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dictionnaries" asp-action="Index">Dictionnaire</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - kata_pendu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>